version: 1.0
jobs:
  deploy:
    steps:
        - npm install -g zcatalyst-cli@beta
        - node cicd/scripts/deploy.js
        - printenv
        - catalyst deploy
stages:
  - name: deploy-stage
    jobs:
      - deploy